name: Build Tauri App

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [created]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      # 1️⃣ Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ Installer Rust (Tauri en a besoin)
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      # 4️⃣ Installer les dépendances Node.js
      - name: Install dependencies
        run: npm ci

      # 5️⃣ Construire l’application Tauri
      - name: Build Tauri App
        run: npm run tauri build

      # 6️⃣ Upload des binaires (multi-plateforme)
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-build-${{ matrix.platform }}
          path: src-tauri/target/release/
