name: Build Tauri App

on:
  release:
    types: [created]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      # 1️⃣ Récupérer le code source
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Installer Rust (nécessaire pour Tauri)
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      # 3️⃣ Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 4️⃣ Installer les dépendances Node.js
      - name: Install dependencies
        run: npm install

      # 5️⃣ Compiler l’application Tauri
      - name: Build Tauri App
        run: npm run tauri build

      # 6️⃣ Sauvegarder les exécutables en tant qu’artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.platform }}
          path: |
            src-tauri/target/release/bundle/**
